[profile.default]
src = 'src'
out = 'artifacts'
libs = ["node_modules", "lib"]
solc = "0.7.6"
fuzz = { runs = 50 }
optimizer_runs = 10_000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config